require("user.colorschemes.tokyonight")
require("user.options")
require("user.keymappings")
require("user.plugins")
require("user.cmp-config")
require("user.lsp")

require("user.alpha-config")
require("user.colorizer-config")
require("user.comment-config")
require("user.dap-config")
require("user.impatient-config")
require("user.notify-config")
require("user.renamer-config")
require("user.spectre-config")
require("user.telescope-config")
require("user.term-config")
require("user.tree-sitter-config")
require("user.ts-context-config")
require("user.vim-project-config")
require("user.vim-zen-config")
require("user.whichkey-config")

require("user.git-config.git-signs")
require("user.git-config.git-blame")
require("user.git-config.git-link")
require("user.airline-config")
require("user.icons")
require("user.functions")
require("user.gps-config")
require("user.hop-config")
require("user.hot-reload-config")
require("user.illuminate-config")
require("user.functions")

require("user.autocmd-config")
require("user.auto-pairs-config")
require("user.indent-line-config")
require("user.phpcs-fixer-config")
require("user.tabnine-config")
require("user.nvim-tree-config")

-- packages
require("user.plugins")
