require("user.colorschemes.tokyonight")
require("user.options")
require("user.keymapping")
require("user.plugins")
require("user.cmp")
require("user.lsp")

require("user.alpha")
require("user.colorizer")
require("user.comment")
require("user.dap")
require("user.impatient")
require("user.lsp")
require("user.notify")
require("user.renamer")
require("user.spectre")
require("user.telescope")
require("user.term")
require("user.tree-sitter")
require("user.ts-context")
require("user.vim-project")
require("user.vim-zen")
require("user.whichkey")

require("user.git-signs")
require("user.git-blame")
require("user.git-link")
require("user.settings.airline")
require("user.dev-icons")
require("user.functions")
require("user.gps")
require("user.hop")
require("user.hot-reload")
require("user.illuminate")
require("user.functions")

require("user.autocmd")
require("user.autopairs")
require("user.indent-line")
require("user.phpcs-fixer")
require("user.tabnine")
require("user.nvim-tree")

-- packages
require("user.plugins")
