local Plug = vim.fn['plug#']

Plug 'joshdick/onedark.vim'
Plug 'andreypopp/vim-colors-plain'
Plug 'antlypls/vim-colors-codeschool'
Plug 'tomasr/molokai'
Plug 'jpo/vim-railscasts-theme'
Plug 'gosukiwi/vim-atom-dark'
Plug 'w0ng/vim-hybrid'
Plug 'morhetz/gruvbox'
Plug 'whatyouhide/vim-gotham'
Plug 'altercation/vim-colors-solarized'
Plug 'NLKNguyen/papercolor-theme'
Plug 'airblade/vim-gitgutter'
Plug 'trevordmiller/nova-vim'
Plug 'noahfrederick/vim-noctu'
Plug 'logico-dev/typewriter'
Plug 'ayu-theme/ayu-vim'
Plug 'gregsexton/Atom'
Plug 'Badacadabra/vim-archery'
Plug 'endel/vim-github-colorscheme'
Plug 'keith/parsec.vim'
Plug('sonph/onehalf', { rtp = 'vim'})
Plug 'connorholyday/vim-snazzy'
Plug 'pveyes/atom-snazzy-clear-syntax'
Plug 'fmoralesc/molokayo'
Plug 'lifepillar/vim-solarized8'
Plug 'ruby-formatter/rufo-vim'
Plug 'arcticicestudio/nord-vim'
Plug 'vim-airline/vim-airline-themes'
Plug 'jonathanfilip/vim-lucius'
Plug('dracula/vim', { as = 'dracula' })

Plug 'folke/tokyonight.nvim'
Plug 'lunarvim/colorschemes' -- A bunch of colorschemes you can try out
Plug 'lunarvim/darkplus.nvim'
Plug 'catppuccin/nvim'
Plug 'rose-pine/neovim'
