#!/usr/bin/env fish

set USER $USER
set JAR /home/$USER/.local/share/nvim/lsp_servers/jdtls/plugins/org.eclipse.equinox.launcher_1.6.400.v20210924-0641.jar
GRADLE_HOME=$HOME/gradle /usr/lib/jvm/java-11-openjdk-amd64/bin/java \
 -Declipse.application=org.eclipse.jdt.ls.core.id1 \
 -Dosgi.bundles.defaultStartLevel=4 \
 -Declipse.product=org.eclipse.jdt.ls.core.product \
 -Dlog.protocol=true \
 -Dlog.level=ALL \
 -Xms1g \
 -Xmx2G \
 -jar $JAR \
 -configuration /home/$USER/.local/share/nvim/lsp_servers/jdtls/config_linux \
 -data /home/$USER/workspace \
 --add-module=ALL-SYSTEM \
 --add-opens java.base/java.util=ALL-UNNAMED \
 --add-opens java.base/java.lang=ALL-UNNAMED 
