return {
  {
    "LazyVim/LazyVim",
    opts = {
      icons = {
        kinds = {
          Array = " ",
          Boolean = "󰨙 ",
          Class = " ",
          Codeium = "󰘦 ",
          Color = " ",
          Control = " ",
          Collapsed = " ",
          -- Constant = "󰏿 ",
          Constant = "ℂ ", -- New icon for Constant
          Constructor = " ",
          Copilot = "",
          Enum = " ",
          EnumMember = " ",
          Event = " ",
          Field = "",
          File = " ",
          Folder = " ",
          Function = "λ ", -- Only override Function
          Interface = " ",
          Key = " ",
          Keyword = " ",
          Method = "",
          Module = " ",
          Namespace = "󰦮 ",
          Null = " ",
          Number = "󰎠 ",
          Object = " ",
          Operator = " ",
          Package = " ",
          Property = " ",
          Reference = " ",
          Snippet = "󱄽 ",
          String = " ",
          Struct = "󰆼 ",
          Supermaven = " ",
          TabNine = "󰏚 ",
          Text = " ",
          TypeParameter = " ",
          Unit = " ",
          Value = " ",
          Variable = " ",
        },
      },
    },
  },
}
