vim.g.php_cs_fixer_rules = "@PSR2" --[[ options: --rules (default:@PSR2) ]]
vim.g.php_cs_fixer_php_path = "php" --[[  Path to PHP ]]
vim.g.php_cs_fixer_enable_default_mapping = 1 --[[  Enable the mapping by default (<leader>pcd) ]]
vim.g.php_cs_fixer_dry_run = 0 --[[  Call command with dry-run option ]]
vim.g.php_cs_fixer_verbose = 0 --[[  Return the output of command if 1, else an inline information. ]]
